services:
  postgres:
    image: postgres:16-alpine
    container_name: onpre-sf-postgres
    environment:
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_DATABASE}
    # ports:
    #   - "127.0.0.1:5432:5432" # Restricted to internal network only
    volumes:
      - ./data/postgres:/var/lib/postgresql/data
    networks:
      - onpre-sf-network
    restart: always

  minio:
    image: minio/minio
    container_name: onpre-sf-minio
    command: server /data --console-address ":9001"
    environment:
      MINIO_ROOT_USER: ${MINIO_ROOT_USER}
      MINIO_ROOT_PASSWORD: ${MINIO_ROOT_PASSWORD}
    ports:
      - "${PORT_MINIO:-9000}:9000"
      - "${PORT_MINIO_CONSOLE:-9001}:9001"
    volumes:
      - ./data/minio:/data
    networks:
      - onpre-sf-network
    restart: always

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: onpre-sf-backend
    ports:
      - "${PORT_BACKEND:-3000}:3000"
    environment:
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_USERNAME=${DB_USERNAME}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_DATABASE=${DB_DATABASE}
      - MINIO_ENDPOINT=minio
      - MINIO_PORT=9000
      - MINIO_ROOT_USER=${MINIO_ROOT_USER}
      - MINIO_ROOT_PASSWORD=${MINIO_ROOT_PASSWORD}
      - MINIO_BUCKET_NAME=${MINIO_BUCKET_NAME}
      - DISCORD_BOT_TOKEN=${DISCORD_BOT_TOKEN}
      - DISCORD_CHANNEL_IDS=${DISCORD_CHANNEL_IDS}
      - ADMIN_USERNAME=${ADMIN_USERNAME}
      - ADMIN_PASSWORD=${ADMIN_PASSWORD}
      - JWT_SECRET=${JWT_SECRET}
    depends_on:
      - postgres
      - minio
    networks:
      - onpre-sf-network
    volumes:
      - ./backend:/usr/src/app
      - /usr/src/app/node_modules
    command: npm run start:dev

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: onpre-sf-frontend
    ports:
      - "${PORT_FRONTEND:-5173}:5173"
    environment:
      - VITE_API_URL=${VITE_API_URL}
    depends_on:
      - backend
    networks:
      - onpre-sf-network
    volumes:
      - ./frontend:/app
      - /app/node_modules
    command: npm run dev -- --host

networks:
  onpre-sf-network:
    driver: bridge

# volumes:
#   postgres_data:
#   minio_data:
